CompileFlags:
  Add: [-D_CLANGD, -D_COSMO_SOURCE, -Wall, -Wextra, -Wconversion, -Wdouble-promotion, -Wno-sign-conversion, -Wno-unused-parameter, -Wno-unused-function, -fmacro-backtrace-limit=1]
Diagnostics:
  Suppress: []
